### PR TITLE
Avoid a panic in combine_for_open

### LINKED ISSUE #2246: [Bug] Unwraping panic when `kzg10::KZG10::<E>::check_degrees_and_bounds` return an error in `sonic_pc::SonicKZG10::combine_for_open`
# Unwraping panic when `kzg10::KZG10::<E>::check_degrees_and_bounds` return an error in `sonic_pc::SonicKZG10::combine_for_open`

**Author(s):** Ronan Thoraval [@Fuzzinglabs](https://github.com/FuzzingLabs/)
**Date:** 14/12/2023

## ****Executive Summary****

In the [`combine_for_open()`](https://github.com/AleoHQ/snarkVM/blob/31d0bb5d0a757f2522449133aa3b0924569bc598/algorithms/src/polycommit/sonic_pc/mod.rs#L266C15-L266C15) function, there is an `unwrap()` on the result of [`check_degrees_and_bound()`](https://github.com/AleoHQ/snarkVM/blob/31d0bb5d0a757f2522449133aa3b0924569bc598/algorithms/src/polycommit/kzg10/mod.rs#L423). [`check_degrees_and_bound()`](https://github.com/AleoHQ/snarkVM/blob/31d0bb5d0a757f2522449133aa3b0924569bc598/algorithms/src/polycommit/kzg10/mod.rs#L423) returns `Ok(())` if the degrees and bound are valid, but return an error otherwise, error that we `unwrap()` in [`combine_for_open()`](https://github.com/AleoHQ/snarkVM/blob/31d0bb5d0a757f2522449133aa3b0924569bc598/algorithms/src/polycommit/sonic_pc/mod.rs#L266C15-L266C15) making the program to panic.

## Vulnerability Details

- **Severity:** Critical
- **Affected Component:** Sonic Commitment Scheme

## Environment

- **Compiler Version:** cargo 1.73.0 (9c4383fb5 2023-08-26)
- **Distro Version:** Ubuntu 23.04

## Steps to Reproduce

There is 3 ways to reach the panic :

1. ``` rust
    use rand::Rng;
    use snarkvm_utilities::rand::TestRng;
    use snarkvm_algorithms::fft::polynomial::*;
    use snarkvm_curves::bls12_377::Fr;
    use snarkvm_algorithms::polycommit::sonic_pc as aleo_sonic;
    use snarkvm_curves::bls12_377::Fq as AleoFq;
    pub type EAleo = snarkvm_curves::templates::bls12::Bls12<snarkvm_curves::bls12_377::Bls12_377Parameters>;
    use snarkvm_algorithms::crypto_hash::PoseidonSponge as AleoPoseidonSponge;
    type AleoSONICKZG10 = aleo_sonic::SonicKZG10<EAleo,AleoPoseidonSponge<AleoFq, 2, 1>>;
    use snarkvm_algorithms::AlgebraicSponge;

    let rng = &mut TestRng::default();

    let d = rng.gen_range(2..42);
    // We generate a random polynomial of degree d
    let p1 = DensePolynomial::<Fr>::rand(d, rng);
    println!("P1 = {:?}",p1);

    let binding = aleo_sonic::Randomness::empty();
    let rands = vec![&binding];

    // First case where the function can unwrap() an error is if the polynomial has a degree bound but the ck hasn't

    let max_degree = 42;
    let srs = AleoSONICKZG10::load_srs(max_degree).unwrap();
    let universal_prover = srs.to_universal_prover().unwrap();

    // The polynomial p1 has degree_bound = 42
    let degree_bound = 42;
    let mut fs_rng = AleoPoseidonSponge::<AleoFq, 2, 1>::new();
    let labeled_polynomials = vec![aleo_sonic::LabeledPolynomial::new("First Case", p1.clone(), degree_bound, None)];

    let supported_degree = max_degree;
    let supported_lagrange_sizes = None;
    let supported_hiding_bound = 0;
    // ck has not enforced_degree_bounds
    let enforced_degree_bounds = None;

    let (ck,_) = AleoSONICKZG10::trim(&srs, supported_degree, supported_lagrange_sizes, supported_hiding_bound, enforced_degree_bounds).unwrap();
    let ck = aleo_sonic::CommitterUnionKey::union(std::iter::once(&ck));

    // And panics
    let _ = AleoSONICKZG10::combine_for_open(&universal_prover, &ck, &labeled_polynomials, rands.clone(), &mut fs_rng); 
    ```

2. ``` rust
    use rand::Rng;
    use snarkvm_utilities::rand::TestRng;
    use snarkvm_algorithms::fft::polynomial::*;
    use snarkvm_curves::bls12_377::Fr;
    use snarkvm_algorithms::polycommit::sonic_pc as aleo_sonic;
    use snarkvm_curves::bls12_377::Fq as AleoFq;
    pub type EAleo = snarkvm_curves::templates::bls12::Bls12<snarkvm_curves::bls12_377::Bls12_377Parameters>;
    use snarkvm_algorithms::crypto_hash::PoseidonSponge as AleoPoseidonSponge;
    type AleoSONICKZG10 = aleo_sonic::SonicKZG10<EAleo,AleoPoseidonSponge<AleoFq, 2, 1>>;
    use snarkvm_algorithms::AlgebraicSponge;

    let rng = &mut TestRng::default();

    let d = rng.gen_range(2..42);
    // We generate a random polynomial of degree d
    let p1 = DensePolynomial::<Fr>::rand(d, rng);
    println!("P1 = {:?}",p1);

    let binding = aleo_sonic::Randomness::empty();
    let rands = vec![&binding];

    // Second case where the function can unwrap() an error is if the polynomial has a degree bound which is not in that of ck

    let max_degree = 42;
    let srs = AleoSONICKZG10::load_srs(max_degree).unwrap();
    let universal_prover = srs.to_universal_prover().unwrap();

    // The polynomial p1 has degree_bound = 42
    let degree_bound = 42;
    let mut fs_rng = AleoPoseidonSponge::<AleoFq, 2, 1>::new();
    let labeled_polynomials = vec![aleo_sonic::LabeledPolynomial::new("Second Case", p1.clone(), degree_bound, None)];
    

    let supported_degree = max_degree;
    let supported_lagrange_sizes = None;
    let supported_hiding_bound = 0;
    // ck has enforced_degree_bounds, but it not contains the degree_bound of p1 (=42)
    let enforced_degree_bounds: Option<&[usize]> = Some(&[1]);

    let (ck,_) = AleoSONICKZG10::trim(&srs, supported_degree, supported_lagrange_sizes, supported_hiding_bound, enforced_degree_bounds).unwrap();
    let ck = aleo_sonic::CommitterUnionKey::union(std::iter::once(&ck));

    // And panics
    let _ = AleoSONICKZG10::combine_for_open(&universal_prover, &ck, &labeled_polynomials, rands.clone(), &mut fs_rng);
    ```

3. ``` rust

    use rand::Rng;
    use snarkvm_utilities::rand::TestRng;
    use snarkvm_algorithms::fft::polynomial::*;
    use snarkvm_curves::bls12_377::Fr;
    use snarkvm_algorithms::polycommit::sonic_pc as aleo_sonic;
    use snarkvm_curves::bls12_377::Fq as AleoFq;
    pub type EAleo = snarkvm_curves::templates::bls12::Bls12<snarkvm_curves::bls12_377::Bls12_377Parameters>;
    use snarkvm_algorithms::crypto_hash::PoseidonSponge as AleoPoseidonSponge;
    type AleoSONICKZG10 = aleo_sonic::SonicKZG10<EAleo,AleoPoseidonSponge<AleoFq, 2, 1>>;
    use snarkvm_algorithms::AlgebraicSponge;

    let rng = &mut TestRng::default();

    let d = rng.gen_range(2..42);
    // We generate a random polynomial of degree d
    let p1 = DensePolynomial::<Fr>::rand(d, rng);
    println!("P1 = {:?}",p1);

    let binding = aleo_sonic::Randomness::empty();
    let rands = vec![&binding];

    // Third case where the function can unwrap() an error is if the polynomial has a degree bound less than its own degree
    
    let max_degree = 42;
    let srs = AleoSONICKZG10::load_srs(max_degree).unwrap();
    let universal_prover = srs.to_universal_prover().unwrap();

    // The polynomial p1 has degree_bound = 1 (less than the degree of p1 (=d>=2))
    let degree_bound = 1;
    let mut fs_rng = AleoPoseidonSponge::<AleoFq, 2, 1>::new();
    let labeled_polynomials = vec![aleo_sonic::LabeledPolynomial::new("Third Case", p1.clone(), degree_bound, None)];

    let supported_degree = max_degree;
    let supported_lagrange_sizes = None;
    let supported_hiding_bound = 0;
    let binding = [degree_bound];
    let enforced_degree_bounds: Option<&[usize]> = Some(&binding);

    let (ck,_) = AleoSONICKZG10::trim(&srs, supported_degree, supported_lagrange_sizes, supported_hiding_bound, enforced_degree_bounds).unwrap();
    let ck = aleo_sonic::CommitterUnionKey::union(std::iter::once(&ck));

    // And panics
    let _ = AleoSONICKZG10::combine_for_open(&universal_prover, &ck, &labeled_polynomials, rands.clone(), &mut fs_rng);
    ``` 

## Root Cause Analysis

In the [`combine_for_open()`](https://github.com/AleoHQ/snarkVM/blob/31d0bb5d0a757f2522449133aa3b0924569bc598/algorithms/src/polycommit/sonic_pc/mod.rs#L266C15-L266C15)function, at [line 280-281](https://github.com/AleoHQ/snarkVM/blob/31d0bb5d0a757f2522449133aa3b0924569bc598/algorithms/src/polycommit/sonic_pc/mod.rs#L280C10-L281C23), there is an `unwrap()` on a value that can be an error, and so and therefore the code panics.

## Detailed Behavior

1. ```
    sh

    thread 'main' panicked at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:525:18:
    called `Result::unwrap()` on an `Err` value: UnsupportedDegreeBound(42)
    stack backtrace:
    0: rust_begin_unwind
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
    1: core::panicking::panic_fmt
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
    2: core::result::unwrap_failed
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
    3: core::result::Result<T,E>::unwrap
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
    4: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_for_open::{{closure}}
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:524:13
    5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:305:13
    6: core::option::Option<T>::map
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:1075:29
    7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:103:26
    8: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_polynomials
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:798:36
    9: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_for_open
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:521:12
    ```

2. ```
    sh
    thread 'main' panicked at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:525:18:
    called `Result::unwrap()` on an `Err` value: UnsupportedDegreeBound(42)
    stack backtrace:
    0: rust_begin_unwind
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
    1: core::panicking::panic_fmt
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
    2: core::result::unwrap_failed
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
    3: core::result::Result<T,E>::unwrap
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
    4: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_for_open::{{closure}}
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:524:13
    5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:305:13
    6: core::option::Option<T>::map
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:1075:29
    7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:103:26
    8: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_polynomials
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:798:36
    9: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_for_open
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:521:12
    ```

3. ```
    sh

    thread 'main' panicked at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:525:18:
    called `Result::unwrap()` on an `Err` value: IncorrectDegreeBound { poly_degree: 34, degree_bound: 1, max_degree: 268435455, label: "Third Case" }
    stack backtrace:
    0: rust_begin_unwind
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
    1: core::panicking::panic_fmt
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
    2: core::result::unwrap_failed
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
    3: core::result::Result<T,E>::unwrap
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
    4: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_for_open::{{closure}}
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:524:13
    5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:305:13
    6: core::option::Option<T>::map
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/option.rs:1075:29
    7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
                at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/iter/adapters/map.rs:103:26
    8: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_polynomials
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:798:36
    9: snarkvm_algorithms::polycommit::sonic_pc::SonicKZG10<E,S>::combine_for_open
                at /home/ronan/Desktop/Projects/ALEO/snarkVM/algorithms/src/polycommit/sonic_pc/mod.rs:521:12
    ```

## Recommendations

Replace the code with something equivalent that handles the error:

``` rust

    let mut inp = Vec::new();

    for (p,r) in labeled_polynomials.into_iter().zip_eq(rands){
        let enforced_degree_bounds: Option<&[usize]> = ck.enforced_degree_bounds.as_deref();

        kzg10::KZG10::<E>::check_degrees_and_bounds(universal_prover.max_degree, enforced_degree_bounds, p)?;
        let challenge = fs_rng.squeeze_short_nonnative_field_element::<E::Fr>();
        inp..push((challenge, p.polynomial().to_dense(), r));
    } 
        
    Ok(Self::combine_polynomials(inp))
```

### PR DESCRIPTION
**Pull request by ljedrz**
This PR introduces a new allocation, but I don't recall seeing that function in the profiles, so it shouldn't be too bad; if we want to remove it, the function can be altered to work on `query_to_labels_map` from `batch_open`, which would remove several other allocations as well.

Fixes #2246.

### CODE REVIEW

File: algorithms/src/polycommit/sonic_pc/mod.rs [hunk 1]
```diff
@@ -266,22 +266,25 @@ impl<E: PairingEngine, S: AlgebraicSponge<E::Fq, 2>> SonicKZG10<E, S> {
...
         fs_rng: &mut S,
     ) -> Result<(DensePolynomial<E::Fr>, Randomness<E>), PCError>
     where
         Randomness<E>: 'a,
         Commitment<E>: 'a,
     {
-        Ok(Self::combine_polynomials(labeled_polynomials.into_iter().zip_eq(rands).map(|(p, r)| {
+        let mut to_combine = Vec::with_capacity(labeled_polynomials.len());
+
+        for (p, r) in labeled_polynomials.zip_eq(rands) {
```
Comment (howardwu) [inline algorithms/src/polycommit/sonic_pc/mod.rs:281]: This `.zip_eq` needs an `ensure!` on the `len()`.

**Review by howardwu — APPROVED** [review]

File: algorithms/src/polycommit/sonic_pc/mod.rs (hunk 1 above)
Comment (ljedrz) [reply algorithms/src/polycommit/sonic_pc/mod.rs:281]: the rebase took care of that ([L278](https://github.com/AleoHQ/snarkVM/pull/2247/files#diff-1c2269e15b2c9eb1b102866e39b60f7149b01d43503a3bdd02081fc7200a358cR278))

**Review by howardwu — APPROVED** [review]
