### PR TITLE
Guard against OOM in the CanonicalDeserialize impl for String

### LINKED ISSUE #1090: [Bug/Security] Out-of-memory (OOM) crash/panic in `ProvingKey::from_bytes_le`
# Out-of-memory (OOM) crash/panic in `ProvingKey::from_bytes_le`

We (@fuzzinglabs) found an Out-of-memory (OOM) issue while fuzzing `ProvingKey::from_bytes_le`.

Using cargo nightly
```sh
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Using cargo stable
```sh
memory allocation of 18374686479671623680 bytes failed
[1]    1622353 abort (core dumped)  RUST_BACKTRACE=1 cargo +stable run
```

## Expected Behavior

An error should be returned instead.

## Your Environment

-  SnarkVM commit: 44b1802589b3cdcd84acc0752210b212f203dfc3
-  Rust Version (nightly): cargo 1.66.0-nightly (082503982 2022-09-13) 
-  Rust Version (stable): cargo 1.63.0 (fd9c4297c 2022-07-01)
-  Computer OS: Ubuntu 20.04

## Steps to Reproduce

Testing program:
``` rust
use snarkvm_compiler::ProvingKey;
use snarkvm_wasm::network::Testnet3;
use snarkvm_wasm::prelude::FromBytes;

pub type CurrentNetwork = Testnet3;

fn main() {
    let data = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255];
    let _ = ProvingKey::<CurrentNetwork>::from_bytes_le(&data);
}
```

Build and run:
``` sh
$ RUST_BACKTRACE=1 cargo +nightly run
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/panicking.rs:142:14
   2: alloc::raw_vec::capacity_overflow
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/raw_vec.rs:518:5
   3: alloc::raw_vec::handle_reserve
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/raw_vec.rs:489:34
   4: alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/raw_vec.rs:285:13
   5: alloc::raw_vec::RawVec<T,A>::reserve
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/raw_vec.rs:289:13
   6: alloc::vec::Vec<T,A>::reserve
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/vec/mod.rs:841:9
   7: alloc::vec::Vec<T,A>::extend_with
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/vec/mod.rs:2400:9
   8: alloc::vec::Vec<T,A>::resize
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/alloc/src/vec/mod.rs:2256:13
   9: bincode::de::read::IoReader<R>::fill_buffer
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/read.rs:144:9
  10: <bincode::de::read::IoReader<R> as bincode::de::read::BincodeRead>::get_byte_buffer
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/read.rs:171:9
  11: bincode::de::Deserializer<R,O>::read_vec
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:96:9
  12: bincode::de::Deserializer<R,O>::read_string
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:100:19
  13: <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_string
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:244:30
  14: serde::de::impls::<impl serde::de::Deserialize for alloc::string::String>::deserialize
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.144/src/de/impls.rs:586:9
  15: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.144/src/de/mod.rs:792:9
  16: bincode::internal::deserialize_from_custom_seed
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:88:5
  17: bincode::internal::deserialize_from_seed
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:65:5
  18: bincode::internal::deserialize_from
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:55:5
  19: bincode::config::Options::deserialize_from
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/config/mod.rs:229:9
  20: bincode::deserialize_from
             at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/lib.rs:129:5
  21: snarkvm_utilities::serialize::impls::<impl snarkvm_utilities::serialize::traits::CanonicalDeserialize for alloc::string::String>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/impls.rs:90:12
  22: <snarkvm_algorithms::polycommit::sonic_pc::polynomial::PolynomialInfo as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/polycommit/sonic_pc/polynomial.rs:30:44
  23: <snarkvm_algorithms::polycommit::sonic_pc::polynomial::LabeledPolynomial<F> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/polycommit/sonic_pc/polynomial.rs:67:44
  24: <snarkvm_algorithms::snark::marlin::ahp::matrices::MatrixArithmetization<F> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/ahp/matrices.rs:118:44
  25: <snarkvm_algorithms::snark::marlin::ahp::indexer::circuit::Circuit<F,MM> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/ahp/indexer/circuit.rs:162:22
  26: snarkvm_utilities::serialize::impls::<impl snarkvm_utilities::serialize::traits::CanonicalDeserialize for alloc::sync::Arc<T>>::deserialize_with_mode
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/impls.rs:301:21
  27: snarkvm_utilities::serialize::traits::CanonicalDeserialize::deserialize_compressed
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/traits.rs:161:9
  28: <snarkvm_algorithms::snark::marlin::data_structures::circuit_proving_key::CircuitProvingKey<E,MM> as snarkvm_utilities::bytes::FromBytes>::read_le
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/data_structures/circuit_proving_key.rs:59:23
  29: snarkvm_compiler::snark::proving_key::bytes::<impl snarkvm_utilities::bytes::FromBytes for snarkvm_compiler::snark::proving_key::ProvingKey<N>>::read_le
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/vm/compiler/src/snark/proving_key/bytes.rs:29:27
  30: snarkvm_utilities::bytes::FromBytes::from_bytes_le
             at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/bytes.rs:78:12
  31: debug::main
             at ./src/main.rs:86:13
  32: core::ops::function::FnOnce::call_once
             at /rustc/a37499ae66ec5fc52a93d71493b78fb141c32f6b/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Detailed behavior (stable + GDB)
``` rust
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff78c8859 in __GI_abort () at abort.c:79
#2  0x0000555555751eb7 in std::sys::unix::abort_internal () at library/std/src/sys/unix/mod.rs:292
#3  0x000055555557f8d7 in std::process::abort () at library/std/src/process.rs:2103
#4  0x000055555574e09e in std::alloc::rust_oom () at library/std/src/alloc.rs:353
#5  0x0000555555766bb7 in alloc::alloc::__alloc_error_handler::__rg_oom () at library/alloc/src/alloc.rs:413
#6  0x0000555555766ba7 in alloc::alloc::handle_alloc_error::rt_error () at library/alloc/src/alloc.rs:379
#7  0x00005555557668f7 in core::ops::function::FnOnce::call_once () at library/core/src/ops/function.rs:248
#8  0x00005555557668e6 in core::intrinsics::const_eval_select () at library/core/src/intrinsics.rs:2376
#9  0x0000555555580306 in alloc::alloc::handle_alloc_error () at library/alloc/src/alloc.rs:383
#10 0x0000555555628e02 in alloc::raw_vec::handle_reserve (result=...) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/raw_vec.rs:489
#11 0x0000555555629750 in alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle (slf=0x7ffffffee678, len=0, additional=18374686479671623680) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/raw_vec.rs:285
#12 0x000055555562971e in alloc::raw_vec::RawVec<T,A>::reserve (self=0x7ffffffee678, len=0, additional=18374686479671623680) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/raw_vec.rs:289
#13 0x0000555555628161 in alloc::vec::Vec<T,A>::reserve (self=0x7ffffffee678, additional=18374686479671623680) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/mod.rs:841
#14 0x00005555555c2eeb in alloc::vec::Vec<T,A>::extend_with (self=0x7ffffffee678, n=18374686479671623680, value=...) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/mod.rs:2396
#15 0x00005555555c473e in alloc::vec::Vec<T,A>::resize (self=0x7ffffffee678, new_len=18374686479671623680, value=0) at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/vec/mod.rs:2252
#16 0x00005555555d035e in bincode::de::read::IoReader<R>::fill_buffer (self=0x7ffffffee670, length=18374686479671623680) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/read.rs:144
#17 0x00005555555d057a in <bincode::de::read::IoReader<R> as bincode::de::read::BincodeRead>::get_byte_buffer (self=0x7ffffffee670, length=18374686479671623680)
    at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/read.rs:171
#18 0x00005555555bbd61 in bincode::de::Deserializer<R,O>::read_vec (self=0x7ffffffee670) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:96
#19 0x00005555555bb98a in bincode::de::Deserializer<R,O>::read_string (self=0x7ffffffee670) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:100
#20 0x00005555555bbdc2 in <&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_string (self=0x7ffffffee670, visitor=...)
    at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/de/mod.rs:244
#21 0x0000555555615566 in serde::de::impls::<impl serde::de::Deserialize for alloc::string::String>::deserialize (deserializer=0x7ffffffee670)
    at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.144/src/de/impls.rs:586
#22 0x0000555555610095 in <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize (self=..., deserializer=0x7ffffffee670)
    at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.144/src/de/mod.rs:792
#23 0x000055555559cbd5 in bincode::internal::deserialize_from_custom_seed (seed=..., reader=..., options=...) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:88
#24 0x000055555559cb3d in bincode::internal::deserialize_from_seed (seed=..., reader=0x7ffffffee8b0, options=...) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:65
#25 0x000055555559cab5 in bincode::internal::deserialize_from (reader=0x7ffffffee8b0, options=...) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/internal.rs:55
#26 0x00005555555ecf1d in bincode::config::Options::deserialize_from (reader=0x7ffffffee8b0, self=...) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/config/mod.rs:229
#27 bincode::deserialize_from (reader=0x7ffffffee8b0) at /home/scop/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-1.3.3/src/lib.rs:129
#28 0x0000555555615459 in snarkvm_utilities::serialize::impls::<impl snarkvm_utilities::serialize::traits::CanonicalDeserialize for alloc::string::String>::deserialize_with_mode (reader=0x7ffffffee8b0, 
    _compress=snarkvm_utilities::serialize::traits::Compress::Yes, _validate=snarkvm_utilities::serialize::traits::Validate::Yes) at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/impls.rs:90
#29 0x000055555559bbd8 in <snarkvm_algorithms::polycommit::sonic_pc::polynomial::PolynomialInfo as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode (reader=0x7ffffffeea58, 
    compress=snarkvm_utilities::serialize::traits::Compress::Yes, validate=snarkvm_utilities::serialize::traits::Validate::Yes) at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/polycommit/sonic_pc/polynomial.rs:30
#30 0x000055555559bfc7 in <snarkvm_algorithms::polycommit::sonic_pc::polynomial::LabeledPolynomial<F> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode (reader=0x7ffffffeecc8, 
    compress=snarkvm_utilities::serialize::traits::Compress::Yes, validate=snarkvm_utilities::serialize::traits::Validate::Yes) at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/polycommit/sonic_pc/polynomial.rs:67
#31 0x00005555555bab4d in <snarkvm_algorithms::snark::marlin::ahp::matrices::MatrixArithmetization<F> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode (reader=0x7fffffff05b8, 
    compress=snarkvm_utilities::serialize::traits::Compress::Yes, validate=snarkvm_utilities::serialize::traits::Validate::Yes) at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/ahp/matrices.rs:118
#32 0x00005555555ff2f7 in <snarkvm_algorithms::snark::marlin::ahp::indexer::circuit::Circuit<F,MM> as snarkvm_utilities::serialize::traits::CanonicalDeserialize>::deserialize_with_mode (reader=0x7fffffff9d98, 
    compress=snarkvm_utilities::serialize::traits::Compress::Yes, validate=snarkvm_utilities::serialize::traits::Validate::Yes)
    at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/ahp/indexer/circuit.rs:162
#33 0x00005555555d6324 in snarkvm_utilities::serialize::impls::<impl snarkvm_utilities::serialize::traits::CanonicalDeserialize for alloc::sync::Arc<T>>::deserialize_with_mode (reader=0x7fffffff9d98, 
    compress=snarkvm_utilities::serialize::traits::Compress::Yes, validate=snarkvm_utilities::serialize::traits::Validate::Yes) at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/impls.rs:301
#34 0x00005555555d6422 in snarkvm_utilities::serialize::traits::CanonicalDeserialize::deserialize_compressed (reader=0x7fffffff9d98) at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/serialize/traits.rs:161
#35 0x00005555555ee802 in <snarkvm_algorithms::snark::marlin::data_structures::circuit_proving_key::CircuitProvingKey<E,MM> as snarkvm_utilities::bytes::FromBytes>::read_le (reader=0x7fffffffb4a0)
    at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/algorithms/src/snark/marlin/data_structures/circuit_proving_key.rs:59
#36 0x00005555555a533c in snarkvm_compiler::snark::proving_key::bytes::<impl snarkvm_utilities::bytes::FromBytes for snarkvm_compiler::snark::proving_key::ProvingKey<N>>::read_le (reader=struct &[u8](size=0))
    at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/vm/compiler/src/snark/proving_key/bytes.rs:29
#37 0x00005555555a54bd in snarkvm_utilities::bytes::FromBytes::from_bytes_le (bytes=struct &[u8](size=488) = {...}) at /home/scop/Documents/aleo/aleo_fuzzing/snarkVM/utilities/src/bytes.rs:78
#38 0x00005555555bd3e5 in debug::fuzz_target (data=struct &[u8](size=488) = {...}) at src/main.rs:15
#39 0x00005555555bd94e in debug::main () at src/main.rs:48

```

### PR DESCRIPTION
**Pull request by ljedrz**
The root cause of the OOM discovered in https://github.com/AleoHQ/snarkVM/issues/1090 is the `CanonicalDeserialize` impl for `String`; the solution is to use custom options in order to limit the maximum number of bytes `bincode` can attempt to deserialize.

The limit was picked arbitrarily and can be set to any other reasonable value.

Fixes https://github.com/AleoHQ/snarkVM/issues/1090.

### CODE REVIEW

**Comment by ljedrz** [comment]
Cc https://github.com/AleoHQ/snarkVM/pull/1092 for the `clippy` job failure; the `parameters` one is unrelated too.

**Review by howardwu — APPROVED** [review]

File: utilities/src/serialize/impls.rs [hunk 1]
```diff
@@ -21,6 +21,7 @@ pub use crate::{
     Vec,
 };
 use crate::{serialize::traits::*, SerializationError};
+use serde::Deserialize;
```
Comment (howardwu) [inline utilities/src/serialize/impls.rs]:
```suggestion

use serde::Deserialize;
```

**Comment by ljedrz** [comment]
this one is new, I'll look at it shortly:
```
---- serialize::impls::test::test_string stdout ----
thread 'serialize::impls::test::test_string' panicked at 'assertion failed: `(left == right)`
  left: `"asdf"`,
 right: `"\0\0\0\0"`', utilities/src/serialize/impls.rs:553:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    serialize::impls::test::test_string
```
edit: ah, it's because - somewhat counter-intuitively - the default `bincode` options are not the defaults everywhere :microscope:

**Comment by ljedrz** [comment]
the CI failures are unrelated
