### PR TITLE
Remove extra closing brace for structs in records

### LINKED ISSUE #1743: [Bug] Nested `Struct` in `Record` have an extra closing bracket `}`
## 🐛 Bug Report

Whenever a program generates `Record` with that contains a `Struct`, an extra closing bracket will be added to the end of the `Struct`. Same for nested `Struct` recursively.

## Steps to Reproduce

All data to reproduce can be found in this transaction, executing a program transition :
https://vm.aleo.org/api/testnet3/transaction/at1d08qvu95lzlv92dsjrv8n4lvel8x9rann2t54py4h80vjy0nxcyqhxrpuq

`transition[0].outputs[0]` decoded with viewkey `AViewKey1hKNmqi83PpwjCTSSUCZT2rX3p3jcktNXzJZnk6rSqq4b` returns :
```
{
    owner: aleo1wamjqlka7d0gazlxdys6n8e8zeee3ymedwvw8elvh7529kwd45rq0plgax.private,
    id: {
        collection_number: 25371715469272213720224343178070736482u128.private
    },
    data: {
        privately_minted: {
        positive: 0u64.private,
        negative: 0u64.private
    }
    },
    royalty_fees: 500u16.private,
    publicizable: true.private,
    updatable: true.private,
    metadata_uri: {
        part0: 140152554740597502496525853903429913932u128.private,
        part1: 134617583084312214720973570367896241221u128.private,
        part2: 104133346941662617879306115050903128141u128.private,
        part3: 153398181356134783820482129834790617088u128.private
    }
    },
    _nonce: 4657518007057346011967333542044959903015797864849889452602278140358226817257group.public
}
```

## Expected Behavior

Return value should be:
```
{
    owner: aleo1wamjqlka7d0gazlxdys6n8e8zeee3ymedwvw8elvh7529kwd45rq0plgax.private,
    id: {
        collection_number: 25371715469272213720224343178070736482u128.private
    },
    data: {
    privately_minted: {
        positive: 0u64.private,
        negative: 0u64.private
    },
    royalty_fees: 500u16.private,
    publicizable: true.private,
    updatable: true.private,
    metadata_uri: {
        part0: 140152554740597502496525853903429913932u128.private,
        part1: 134617583084312214720973570367896241221u128.private,
        part2: 104133346941662617879306115050903128141u128.private,
        part3: 153398181356134783820482129834790617088u128.private
    },
    _nonce: 4657518007057346011967333542044959903015797864849889452602278140358226817257group.public
}
```

## Environment
Testnet3

### PR DESCRIPTION
**Pull request by HarukaMa**
## Motivation

Remove the extra closing brace on every struct. Fixes #1743.

## Test Plan

There should be a test case for this as the output is frequently used by end users.
<sup>but i still didn't write one</sup>

## Related PRs

/

### CODE REVIEW

File: console/program/src/data/record/entry/parse.rs [hunk 1]
```diff
@@ -193,7 +193,7 @@ impl<N: Network> Entry<N, Plaintext<N>> {
                                 // Print the last member without a comma.
```
Comment (acoglio) [inline console/program/src/data/record/entry/parse.rs]:
```suggestion
                                // If this inner struct is the last member of the outer struct, print the closing brace of the outer struct.
```

File: console/program/src/data/record/entry/parse.rs [hunk 2]
```diff
@@ -193,7 +193,7 @@ impl<N: Network> Entry<N, Plaintext<N>> {
...
                                 true => write!(f, "\n{:indent$}}}", "", indent = depth * INDENT),
                                 // Print the member with a comma.
```
Comment (acoglio) [inline console/program/src/data/record/entry/parse.rs]:
```suggestion
                                // Otherwise, print a comma after the inner struct, because the outer struct has more members after this one.
```

**Review by acoglio — APPROVED** [review]
Thanks!

**Review by d0cd — APPROVED** [review]
LGTM!
